sonar.projectKey=Streamlined-asylum-admin
sonar.projectName=Streamlined-asylum-admin
sonar.sources=apps,assets/js,bin,utils
sonar.exclusions=bin/*,coverage/*,node_modules/*,assets/js/*,apps/common/views/static/robots.html, apps/saa/index.js, apps/saa/fields/index.js
sonar.coverage.exclusions=apps/common/index.js
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
