sonar.projectKey=Streamlined-asylum-admin
sonar.projectName=Streamlined-asylum-admin
sonar.sources=apps,assets/js,bin,utils
sonar.exclusions=bin/*,coverage/*,node_modules/*,assets/js/*,apps/common/views/static/robots.html, apps/saa/index.js
sonar.coverage.exclusions=apps/**/index.js,apps/**/fields/**/*.js
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.cpd.exclusions=apps/**/fields/**/*.js
